"""
Data models used throughout the Real-Time Logistics Operations Platform.

These models define the structure of data generated by the shipment
generator before it is serialized and sent to Kafka.
"""

from dataclasses import dataclass
from typing import Optional


@dataclass
class ShipmentEvent:
    """
    Represents a single shipment event produced by the Transportation Management System (TMS).
    """

    event_id: str
    event_timestamp: str

    shipment_id: str
    order_id: str

    event_type: str
    shipment_status: str

    facility_type: Optional[str]
    facility_id: Optional[str]

    estimated_delivery_time: str

    latitude: float
    longitude: float


@dataclass
class ActiveShipment:
    """
    Internal in-memory representation of a shipment that is currently
    progressing through its lifecycle.

    Note : This object is NOT sent to Kafka.
           It is used only by shipment_generator.py to maintain shipment state.
    """

    shipment_id: str
    order_id: str

    warehouse_id: str
    delivery_station_id: str
    route_id: str
    vehicle_id: str

    estimated_delivery_time: str

    current_step: int

    latitude: float
    longitude: float

    is_delayed: bool
    delay_minutes: int